package com.flasskdev.vibe.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class VibeStrings(
    // Auth & Nickname & Verification
    val createAccount: String,
    val welcomeBack: String,
    val emailLabel: String,
    val usernameLabel: String,
    val emailInvalidFormat: String,
    val continueBtn: String,
    val verificationTitle: String,
    val verificationSubtitle: (String) -> String,
    val verifyBtn: String,
    val verifyLoading: String,
    val codeInvalid: String,
    val nicknameTitle: String,
    val nicknameLabel: String,
    val saveBtn: String,
    val saveLoading: String,
    val errorSaving: String,
    val freezedAcc: String,
    val bannedAcc: String,

    // Main Container & Tabs
    val tabChats: String,
    val tabSettings: String,
    val tabProfile: String,
    
    // Profile
    val profileTitle: String,
    val statusOnline: String,
    val statusBot: String,
    val statusUnknown: String,
    val actionForward: String,
    val draftLabel: String,
    val badgeVerified: String,
    val badgeDeveloper: String,
    val badgeBot: String,
    val aboutLabel: String,
    val registerDateLabel: String,
    val btnTheme: String,
    val themeDark: String,
    val themeLight: String,
    val btnLanguage: String,
    val btnLogout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmText: String,
    val logoutCancel: String,
    val logoutConfirm: String,
    val userLabel: String,
    
    // Chats
    val chatsTitle: String,
    val chatsEmptyTitle: String,
    val chatsEmptySubtitle: String,
    val searchPlaceholder: String,
    val globalSearchResults: String,
    val typing: String,
    val connecting: String,
    val waitingForNetwork: String,
    val monthsShort: List<String>,
    
    // Last Seen
    val dateToday: String,
    val dateYesterday: String,
    val lastSeenRecently: String,
    val lastSeenLongAgo: String,
    val lastSeenInWeek: String,
    val lastSeenInMonth: String,
    val lastSeenToday: (String) -> String,
    val lastSeenYesterday: (String) -> String,
    val lastSeenDate: (String, String) -> String,

    // Chat Screen
    val backBtn: String,
    val messagePlaceholder: String,
    val replyTo: String,
    val emptyChat: String,
    val chatHistoryCleared: String,
    val chatHistoryEmpty: String,
    val deletedAcc: String,

    // Onboarding
    val onboardingPages: List<Pair<String, String>>,
    
    // Chat Actions
    val selectedMessagesCount: (Int) -> String,
    val deleteMessagesTitle: String,
    val deleteMessagesText: (Int) -> String,
    val deleteForEveryone: (String) -> String,
    val deleteForEveryoneAlsoMine: (String) -> String,
    val deleteBtn: String,
    val cancelBtn: String,
    val forwardMessageTitle: String,
    val noRecentChats: String,
    val editMessageTitle: String,
    val sendBtn: String,
    val forwardedFrom: (String) -> String,
    val replyDefault: String,
    
    // Pinned messages and others
    val pinnedMessage: String,
    val pinnedMessages: String,
    val pinMessage: String,
    val pinMessageConfirm: String,
    val unpinMessage: String,
    val unpinMessageConfirm: String,
    val unpinAll: String,
    val unpinAllConfirm: String,
    val forBoth: (String) -> String,
    val pin: String,
    val unpin: String,
    val you: String,
    val edit: String,
    
    // Settings & Profile editing
    val usernameTaken: String,
    val usernameAvailable: String,
    val usernameDescription: String,
    val usernameMinLength: String,
    val nicknameDescription: String,
    val bioDescription: String,
    val doneBtn: String,
    
    // Chat restrictions & status
    val userRestrictedMessaging: String,
    val userHiddenAccount: String,
    val editedLabel: String,
    
    // Mute
    val muteNotifications: String,
    val unmuteNotifications: String,
    
    // System messages
    val pinnedMessageSystemText: (String, String) -> String,
    
    // Privacy settings
    val privacyActivityTitle: String,
    val privacyActivityDesc: String,
    val privacyAvatarTitle: String,
    val privacyAvatarDesc: String,
    val privacyForwardedTitle: String,
    val privacyForwardedDesc: String,
    val privacyMessagesTitle: String,
    val privacyMessagesDesc: String,
    val privacyStatusTitle: String,
    val privacyStatusDesc: String,
    
    // Settings sections
    val settingsPrivacy: String,
    val settingsAccount: String,
    val settingsDevices: String,
    val settingsPasscode: String,
    
    // Profile screen extras
    val usernameCopied: String,
    val addAvatar: String,
    val choosePhoto: String,
    
    // Media types
    val typeVideo: String,
    val typeVideoMessage: String,
    val typeAudio: String,
    val typeFile: String,
    val typeVoice: String,
    
    // Media player
    val playerPlaylist: String,
    val playerSearchTracks: String,
    val playerNowPlaying: String,
    
    // Profile media sections
    val sectionPhotosVideos: String,
    val sectionFiles: String,
    val sectionMusic: String,
    val sectionVoice: String,
    val profileSearchFiles: String,
    
    // Downloads
    val actionDownload: String,
    val actionDownloadSelected: String,
    
    // Auth screen
    val switchSignIn: String,
    val switchSignUp: String,
    val accountDeleted: String,
    val accountFrozen: String,
    val accountBannedMessage: String,
    val accountFrozenMessage: String,
    
    // Text formatting
    val formatCopy: String,
    val formatCut: String,
    val formatFormat: String,
    val formatBold: String,
    val formatItalic: String,
    val formatBoldItalic: String,
    val formatStrikethrough: String,
    val formatUnderline: String,
    val formatMonospace: String,
    val formatLink: String,
    val formatTextColor: String,
    val formatSpoiler: String,
    val formatQuote: String,
    val formatLinkUrlHint: String,
    val formatColorHint: String,
    val formatPreview: String,
    val formatCopied: String,
    val formatReadMore: String,
    val formatCollapse: String,
    
    // Attachment menu
    val attachPhotoVideo: String,
    val attachFile: String,
    val attachTitle: String,
    
    // Photo viewer
    val photoViewer: String,
    val photoOf: (Int, Int) -> String,
    
    // Message context menu
    val actionCopy: String,
    val actionReport: String,
    
    val locale: String
)

val ruStrings = VibeStrings(
    createAccount = "Создание аккаунта",
    welcomeBack = "С возвращением",
    emailLabel = "ПОЧТА",
    usernameLabel = "ЮЗЕРНЕЙМ",
    emailInvalidFormat = "НЕВЕРНЫЙ ФОРМАТ",
    continueBtn = "ПРОДОЛЖИТЬ",
    verificationTitle = "Введите код",
    verificationSubtitle = { email -> "Мы отправили 6-значный код на вашу почту\n$email" },
    verifyBtn = "ПОДТВЕРДИТЬ",
    verifyLoading = "ПРОВЕРКА...",
    codeInvalid = "Неверный код",
    nicknameTitle = "Как вас зовут?",
    nicknameLabel = "ВАШ НИКНЕЙМ",
    saveBtn = "ПРОДОЛЖИТЬ",
    saveLoading = "СОХРАНЕНИЕ...",
    errorSaving = "Ошибка при сохранении",
    tabChats = "Чаты",
    tabSettings = "Настройки",
    tabProfile = "Профиль",
    profileTitle = "Профиль",
    deletedAcc = "Удаленный аккаунт",
    statusOnline = "В сети",
    statusBot = "Бот",
    statusUnknown = "Неизвестно",
    actionForward = "Переслать",
    badgeVerified = "Пользователь верифицирован командой Vibe.",
    badgeDeveloper = "Член команды разработчиков Vibe.",
    badgeBot = "Просто бот.",
    freezedAcc = "Аккаунт заморожен за нарушение правил.",
    bannedAcc = "Аккаунт заблокирован за нарушение правил.",
    aboutLabel = "Описание",
    registerDateLabel = "Дата регистрации",
    btnTheme = "Тема",
    themeDark = "Темная",
    themeLight = "Светлая",
    btnLanguage = "Язык",
    btnLogout = "Выйти из аккаунта",
    logoutConfirmTitle = "Выход из аккаунта",
    logoutConfirmText = "Вы уверены, что хотите выйти из аккаунта?",
    logoutCancel = "Отмена",
    logoutConfirm = "Выйти",
    userLabel = "Пользователь",
    chatsTitle = "Чаты",
    chatsEmptyTitle = "Нет чатов",
    chatsEmptySubtitle = "Начните переписку!",
    searchPlaceholder = "Поиск...",
    globalSearchResults = "Глобальный поиск",
    typing = "Печатает",
    connecting = "Соединение",
    waitingForNetwork = "Ожидание сети",
    monthsShort = listOf("янв", "фев", "мар", "апр", "мая", "июн", "июл", "авг", "сен", "окт", "ноя", "дек"),
    dateToday = "Сегодня",
    dateYesterday = "Вчера",
    lastSeenRecently = "Был(а) недавно",
    lastSeenLongAgo = "Был(а) очень давно",
    lastSeenInWeek = "Был(а) на этой неделе",
    lastSeenInMonth = "Был(а) в этом месяце",
    lastSeenToday = { time -> "Был(а) сегодня в $time" },
    lastSeenYesterday = { time -> "Был(а) вчера в $time" },
    lastSeenDate = { date, time -> "Был(а) $date в $time" },
    backBtn = "Назад",
    draftLabel = "Черновик: ",
    messagePlaceholder = "Сообщение...",
    replyTo = "Ответить",
    emptyChat = "Здесь пока пусто...",
    chatHistoryCleared = "История очищена",
    chatHistoryEmpty = "История пуста",
    onboardingPages = listOf(
        "Безопасность данных" to "Ваше общение защищено шифрованием военного уровня.",
        "Скорость света" to "Протоколы нового поколения для мгновенной доставки сообщений.",
        "Универсальная синхронизация" to "Вся ваша история данных доступна на каждом устройстве.",
        "Глобальные сообщества" to "Масштабируйте сообщества до миллионов активных участников.",
        "Уникальный Вайб" to "Настройте каждый аспект вашего мессенджера под себя."
    ),
    selectedMessagesCount = { count -> "Выбрано: $count" },
    deleteMessagesTitle = "Удалить сообщения?",
    deleteMessagesText = { count -> "Вы собираетесь удалить $count сообщений." },
    deleteForEveryone = { name -> "Также удалить для $name" },
    deleteForEveryoneAlsoMine = { name -> "Также удалить свои сообщения для $name" },
    deleteBtn = "Удалить",
    cancelBtn = "Отмена",
    forwardMessageTitle = "Переслать сообщение",
    noRecentChats = "Нет недавних чатов",
    editMessageTitle = "Редактирование сообщения",
    sendBtn = "Отправить",
    forwardedFrom = { name -> "Переслано от $name" },
    replyDefault = "Ответ",
    pinnedMessage = "Закрепленное сообщение",
    pinnedMessages = "Закрепленные сообщения",
    pinMessage = "Закрепить сообщение",
    pinMessageConfirm = "Вы действительно хотите закрепить это сообщение?",
    unpinMessage = "Открепить сообщение",
    unpinMessageConfirm = "Вы действительно хотите открепить это сообщение?",
    unpinAll = "Открепить все",
    unpinAllConfirm = "Открепить все сообщения в этом чате?",
    forBoth = { name -> "Также для $name" },
    pin = "Закрепить",
    unpin = "Открепить",
    you = "Вы",
    edit = "Изменить",
    usernameTaken = "Этот юзернейм уже занят",
    usernameAvailable = "Юзернейм свободен",
    usernameDescription = "Вы можете выбрать уникальное имя пользователя в Vibe. Если вы это сделаете, другие люди смогут найти вас по этому имени и связаться с вами, не зная вашего номера телефона.",
    usernameMinLength = "Минимальная длина 4 символа",
    nicknameDescription = "Ваше имя, которое будет отображаться всем пользователям. Постарайтесь выбрать узнаваемое имя, чтобы друзья могли легко вас найти.",
    bioDescription = "Напишите немного о себе. Эта информация будет видна другим пользователям в вашем профиле.",
    doneBtn = "Готово",
    userRestrictedMessaging = "Пользователь ограничил круг общения",
    userHiddenAccount = "Пользователь скрыл аккаунт",
    editedLabel = " (изменено)",
    muteNotifications = "Выключить уведомления",
    unmuteNotifications = "Включить уведомления",
    pinnedMessageSystemText = { sender, content -> "$sender закрепил(а) сообщение: \"$content\"" },
    privacyActivityTitle = "Статус активности",
    privacyActivityDesc = "Кто может видеть, когда вы в последний раз были в сети. Если вы скроете свой статус активности, вы не сможете видеть статус других пользователей (будет отображаться примерное время).",
    privacyAvatarTitle = "Аватарка",
    privacyAvatarDesc = "Кто может видеть вашу аватарку. Для остальных будет отображаться первая буква вашего имени на синем фоне.",
    privacyForwardedTitle = "Пересланные сообщения",
    privacyForwardedDesc = "Кто может переходить на ваш профиль из пересланных сообщений.",
    privacyMessagesTitle = "Сообщения",
    privacyMessagesDesc = "Кто может отправлять вам сообщения. Пользователи, которым это запрещено, увидят надпись «Пользователь ограничил круг общения».",
    privacyStatusTitle = "Статус",
    privacyStatusDesc = "Кто может видеть блок «О себе» в вашем профиле.",
    settingsPrivacy = "Приватность",
    settingsAccount = "Аккаунт",
    settingsDevices = "Устройства",
    settingsPasscode = "Код-пароль",
    usernameCopied = "Юзернейм скопирован",
    addAvatar = "Добавить аватарку",
    choosePhoto = "Выбрать фото",
    switchSignIn = "Уже есть аккаунт? Войти",
    switchSignUp = "Нет аккаунта? Создать",
    accountDeleted = "Удаленный аккаунт",
    accountFrozen = "Замороженный аккаунт",
    accountBannedMessage = "Ваш аккаунт был заблокирован за нарушение правил.",
    accountFrozenMessage = "Ваш аккаунт был заморожен модератором.",
    typeVideo = "Видео",
    typeVideoMessage = "Видеосообщение",
    typeAudio = "Аудиофайл",
    typeFile = "Файл",
    typeVoice = "Голосовое сообщение",
    playerPlaylist = "Плейлист чата",
    playerSearchTracks = "Поиск треков",
    playerNowPlaying = "Сейчас играет",
    sectionPhotosVideos = "Фото и видео",
    sectionFiles = "Файлы",
    sectionMusic = "Музыка",
    sectionVoice = "Голосовые",
    profileSearchFiles = "Поиск файлов",
    actionDownload = "Скачать",
    actionDownloadSelected = "Скачать выбранные",
    formatCopy = "Скопировать",
    formatCut = "Вырезать",
    formatFormat = "Форматировать",
    formatBold = "Жирный",
    formatItalic = "Курсив",
    formatBoldItalic = "Жирный курсив",
    formatStrikethrough = "Зачеркнутый",
    formatUnderline = "Подчеркнутый",
    formatMonospace = "Моноширинный",
    formatLink = "Ссылка",
    formatTextColor = "Цвет текста",
    formatSpoiler = "Спойлер",
    formatQuote = "Цитата",
    formatLinkUrlHint = "Введите URL",
    formatColorHint = "Введите HEX (напр. #FF5733)",
    formatPreview = "Предпросмотр",
    formatCopied = "Скопировано",
    formatReadMore = "Читать далее",
    formatCollapse = "Свернуть",
    attachPhotoVideo = "Фото и видео",
    attachFile = "Файл",
    attachTitle = "Вложения",
    photoViewer = "Просмотр фото",
    photoOf = { current, total -> "$current из $total" },
    actionCopy = "Скопировать текст",
    actionReport = "Пожаловаться",
    locale = "ru"
)

val enStrings = VibeStrings(
    createAccount = "Create Account",
    welcomeBack = "Welcome Back",
    emailLabel = "EMAIL",
    usernameLabel = "USERNAME",
    emailInvalidFormat = "INVALID FORMAT",
    continueBtn = "CONTINUE",
    verificationTitle = "Enter Code",
    verificationSubtitle = { email -> "We sent a 6-digit code to\n$email" },
    verifyBtn = "VERIFY",
    verifyLoading = "VERIFYING...",
    codeInvalid = "Invalid code",
    nicknameTitle = "What's your name?",
    nicknameLabel = "YOUR NAME",
    saveBtn = "CONTINUE",
    saveLoading = "SAVING...",
    errorSaving = "Error saving",
    tabChats = "Chats",
    tabSettings = "Settings",
    tabProfile = "Profile",
    profileTitle = "Profile",
    deletedAcc = "Deleted account",
    statusOnline = "Online",
    statusBot = "Bot",
    statusUnknown = "Unknown",
    actionForward = "Forward",
    badgeVerified = "Verified by Vibe Team.",
    badgeDeveloper = "Vibe Developer Team member.",
    badgeBot = "Just a bot.",
    freezedAcc = "Account frozen for violating the rules.",
    bannedAcc = "Account banned for violating the rules.",
    aboutLabel = "About",
    registerDateLabel = "Joined",
    btnTheme = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    btnLanguage = "Language",
    btnLogout = "Log Out",
    logoutConfirmTitle = "Log Out",
    logoutConfirmText = "Are you sure you want to log out?",
    logoutCancel = "Cancel",
    logoutConfirm = "Log Out",
    userLabel = "User",
    chatsTitle = "Chats",
    chatsEmptyTitle = "No chats",
    chatsEmptySubtitle = "Start a conversation!",
    searchPlaceholder = "Search...",
    globalSearchResults = "Global Search Results",
    typing = "Typing",
    connecting = "Connecting",
    waitingForNetwork = "Waiting for network",
    monthsShort = listOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
    dateToday = "Today",
    dateYesterday = "Yesterday",
    lastSeenRecently = "Last seen recently",
    lastSeenLongAgo = "Last seen a long time ago",
    lastSeenInWeek = "Last seen this week",
    lastSeenInMonth = "Last seen this month",
    lastSeenToday = { time -> "Last seen today at $time" },
    lastSeenYesterday = { time -> "Last seen yesterday at $time" },
    lastSeenDate = { date, time -> "Last seen $date at $time" },
    backBtn = "Back",
    draftLabel = "Draft: ",
    messagePlaceholder = "Message...",
    replyTo = "Reply",
    emptyChat = "It's empty here...",
    chatHistoryCleared = "History cleared",
    chatHistoryEmpty = "History is empty",
    onboardingPages = listOf(
        "Data Shield" to "Your communication is locked with military-grade encryption.",
        "Light Speed" to "Next-gen protocols for instant message propagation.",
        "Universal Sync" to "Your entire data history available on every device.",
        "Global Hubs" to "Scale communities to millions of active nodes.",
        "Unique Vibe" to "Tailor every aspect of your messaging experience."
    ),
    selectedMessagesCount = { count -> "Selected: $count" },
    deleteMessagesTitle = "Delete messages?",
    deleteMessagesText = { count -> "You are about to delete $count messages." },
    deleteForEveryone = { name -> "Also delete for $name" },
    deleteForEveryoneAlsoMine = { name -> "Also delete my messages for $name" },
    deleteBtn = "Delete",
    cancelBtn = "Cancel",
    forwardMessageTitle = "Forward message",
    noRecentChats = "No recent chats",
    editMessageTitle = "Edit message",
    sendBtn = "Send",
    forwardedFrom = { name -> "Forwarded from $name" },
    replyDefault = "Reply",
    pinnedMessage = "Pinned message",
    pinnedMessages = "Pinned messages",
    pinMessage = "Pin message",
    pinMessageConfirm = "Are you sure you want to pin this message?",
    unpinMessage = "Unpin message",
    unpinMessageConfirm = "Are you sure you want to unpin this message?",
    unpinAll = "Unpin all",
    unpinAllConfirm = "Unpin all messages in this chat?",
    forBoth = { name -> "Also for $name" },
    pin = "Pin",
    unpin = "Unpin",
    you = "You",
    edit = "Edit",
    usernameTaken = "This username is already taken",
    usernameAvailable = "Username is available",
    usernameDescription = "You can choose a unique username for Vibe. Other people will be able to find you by this name and contact you without knowing your phone number.",
    usernameMinLength = "Minimum 4 characters",
    nicknameDescription = "Your display name visible to all users. Try to choose a recognizable name so friends can easily find you.",
    bioDescription = "Write a bit about yourself. This information will be visible to other users on your profile.",
    doneBtn = "Done",
    userRestrictedMessaging = "This user has restricted who can message them",
    userHiddenAccount = "User has hidden their account",
    editedLabel = " (edited)",
    muteNotifications = "Mute notifications",
    unmuteNotifications = "Unmute notifications",
    pinnedMessageSystemText = { sender, content -> "$sender pinned a message: \"$content\"" },
    privacyActivityTitle = "Activity status",
    privacyActivityDesc = "Who can see when you were last online. If you hide your activity status, you won't be able to see other users' status (approximate time will be shown).",
    privacyAvatarTitle = "Avatar",
    privacyAvatarDesc = "Who can see your avatar. Others will see the first letter of your name on a blue background.",
    privacyForwardedTitle = "Forwarded messages",
    privacyForwardedDesc = "Who can navigate to your profile from forwarded messages.",
    privacyMessagesTitle = "Messages",
    privacyMessagesDesc = "Who can send you messages. Users who are restricted will see a notice that you've limited who can contact you.",
    privacyStatusTitle = "Status",
    privacyStatusDesc = "Who can see the 'About' section in your profile.",
    settingsPrivacy = "Privacy",
    settingsAccount = "Account",
    settingsDevices = "Devices",
    settingsPasscode = "Passcode",
    usernameCopied = "Username copied",
    addAvatar = "Add avatar",
    choosePhoto = "Choose photo",
    switchSignIn = "Already have an account? Sign In",
    switchSignUp = "New here? Create Account",
    accountDeleted = "Deleted account",
    accountFrozen = "Frozen account",
    accountBannedMessage = "Your account has been banned for violating the rules.",
    accountFrozenMessage = "Your account has been frozen by a moderator.",
    typeVideo = "Video",
    typeVideoMessage = "Video message",
    typeAudio = "Audio file",
    typeFile = "File",
    typeVoice = "Voice message",
    playerPlaylist = "Chat playlist",
    playerSearchTracks = "Search tracks",
    playerNowPlaying = "Now playing",
    sectionPhotosVideos = "Photos and videos",
    sectionFiles = "Files",
    sectionMusic = "Music",
    sectionVoice = "Voice messages",
    profileSearchFiles = "Search files",
    actionDownload = "Download",
    actionDownloadSelected = "Download selected",
    formatCopy = "Copy",
    formatCut = "Cut",
    formatFormat = "Format",
    formatBold = "Bold",
    formatItalic = "Italic",
    formatBoldItalic = "Bold Italic",
    formatStrikethrough = "Strikethrough",
    formatUnderline = "Underline",
    formatMonospace = "Monospace",
    formatLink = "Link",
    formatTextColor = "Text Color",
    formatSpoiler = "Spoiler",
    formatQuote = "Quote",
    formatLinkUrlHint = "Enter URL",
    formatColorHint = "Enter HEX (e.g. #FF5733)",
    formatPreview = "Preview",
    formatCopied = "Copied",
    formatReadMore = "Read more",
    formatCollapse = "Collapse",
    attachPhotoVideo = "Photos & Videos",
    attachFile = "File",
    attachTitle = "Attachments",
    photoViewer = "Photo viewer",
    photoOf = { current, total -> "$current of $total" },
    actionCopy = "Copy text",
    actionReport = "Report",
    locale = "en"
)

val LocalVibeStrings = compositionLocalOf { ruStrings }
